<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591;AD0001;SA0000;SA1200;SA1600;SA1633;SA1309;SA1201;SA1210;SA1101</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\NotificationService.Domain\NotificationService.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Diagnostics" Version="8.4.0" />
        <PackageReference Include="Handlebars.Net" Version="2.1.6" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.3" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.3" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.3" />
    </ItemGroup>

</Project>
