<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591;AD0001</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\QuestionManagementService.Domain\QuestionManagementService.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Diagnostics" Version="8.4.0" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.3" />
    </ItemGroup>

</Project>
