// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuestionManagementService.Infrastructure.Database.Context;

#nullable disable

namespace QuestionManagementService.Infrastructure.Database.Migrations
{
    [DbContext(typeof(QuestionDbContext))]
    [Migration("20260222044242_Create_InitialTables")]
    partial class Create_InitialTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuestionManagementService.Domain.Entities.AnswerOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("IsCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_correct");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("Ordinal")
                        .HasDatabaseName("ix_answer_options_ordinal");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_answer_options_question_id");

                    b.ToTable("answer_options", (string)null);
                });

            modelBuilder.Entity("QuestionManagementService.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte>("Difficulty")
                        .HasColumnType("smallint")
                        .HasColumnName("difficulty");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("QuestionBankId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_bank_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_questions_category");

                    b.HasIndex("Difficulty")
                        .HasDatabaseName("ix_questions_difficulty");

                    b.HasIndex("QuestionBankId")
                        .HasDatabaseName("ix_questions_question_bank_id");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("QuestionManagementService.Domain.Entities.QuestionBank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_question_banks_name");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_question_banks_owner_id");

                    b.ToTable("question_banks", (string)null);
                });

            modelBuilder.Entity("QuestionManagementService.Domain.Entities.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<byte>("PassingScore")
                        .HasColumnType("smallint")
                        .HasColumnName("passing_score");

                    b.Property<Guid>("QuestionBankId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_bank_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("QuestionBankId")
                        .HasDatabaseName("ix_tests_question_bank_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_tests_status");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_tests_template_id");

                    b.ToTable("tests", (string)null);
                });

            modelBuilder.Entity("QuestionManagementService.Domain.Entities.TestQuestion", b =>
                {
                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_id");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.HasKey("TestId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("test_questions", (string)null);
                });

            modelBuilder.Entity("QuestionManagementService.Domain.Entities.TestTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Configuration")
                        .HasColumnType("JSONB")
                        .HasColumnName("configuration");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DefaultDuration")
                        .HasColumnType("integer")
                        .HasColumnName("default_duration");

                    b.Property<byte>("DefaultPassingScore")
                        .HasColumnType("smallint")
                        .HasColumnName("default_passing_score");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_test_templates_name");

                    b.ToTable("test_templates", (string)null);
                });

            modelBuilder.Entity("QuestionManagementService.Domain.Entities.AnswerOption", b =>
                {
                    b.HasOne("QuestionManagementService.Domain.Entities.Question", "Question")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_answer_options_questions");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuestionManagementService.Domain.Entities.Question", b =>
                {
                    b.HasOne("QuestionManagementService.Domain.Entities.QuestionBank", "QuestionBank")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionBankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questions_question_banks");

                    b.Navigation("QuestionBank");
                });

            modelBuilder.Entity("QuestionManagementService.Domain.Entities.Test", b =>
                {
                    b.HasOne("QuestionManagementService.Domain.Entities.QuestionBank", "QuestionBank")
                        .WithMany()
                        .HasForeignKey("QuestionBankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tests_question_banks");

                    b.HasOne("QuestionManagementService.Domain.Entities.TestTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .HasConstraintName("fk_tests_test_templates");

                    b.Navigation("QuestionBank");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("QuestionManagementService.Domain.Entities.TestQuestion", b =>
                {
                    b.HasOne("QuestionManagementService.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_questions_questions");

                    b.HasOne("QuestionManagementService.Domain.Entities.Test", "Test")
                        .WithMany("TestQuestions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_questions_tests");

                    b.Navigation("Question");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("QuestionManagementService.Domain.Entities.Question", b =>
                {
                    b.Navigation("AnswerOptions");
                });

            modelBuilder.Entity("QuestionManagementService.Domain.Entities.QuestionBank", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("QuestionManagementService.Domain.Entities.Test", b =>
                {
                    b.Navigation("TestQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
