<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <NoWarn>$(NoWarn);NU1902;NU1903;NU1510</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="8.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="FluentAssertions" Version="8.8.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.3" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
        <PackageReference Include="Testcontainers.PostgreSql" Version="4.10.0" />
        <PackageReference Include="xunit" Version="2.9.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\FileStorageService.Application\FileStorageService.Application.csproj" />
        <ProjectReference Include="..\..\src\FileStorageService.Domain\FileStorageService.Domain.csproj" />
        <ProjectReference Include="..\..\src\FileStorageService.Infrastructure.Database\FileStorageService.Infrastructure.Database.csproj" />
        <ProjectReference Include="..\..\src\FileStorageService.WebApi\FileStorageService.WebApi.csproj" />
    </ItemGroup>

</Project>
